# 马赛克

In [1]:
import cv2
import numpy as np

In [4]:
img=cv2.imread('./einstein.jpg')
print(img.shape)
cv2.imshow('einstein',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(534, 400, 3)


## 马赛克方式一

In [7]:
ratio=10
img2=cv2.resize(img,(int(img.shape[1]/ratio),int(img.shape[0]/ratio)))
img3=np.repeat(img2,ratio,axis=0)
img4=np.repeat(img3,ratio,axis=1)
cv2.imshow('einstein',img4)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
#repeat的功能：
print(np.repeat([1,2,3],3))
print(np.repeat([[1,2,3],[4,5,6]],3,axis=0))

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


## 马赛克方式二

In [ ]:
img=cv2.imread('./einstein.jpg')

In [8]:
ratio=10
img2=img[::ratio,::ratio]
# cv2.namedWindow('einstein',flags=cv2.WINDOW_NORMAL)
# cv2.resizeWindow('einstein',img.shape[1],img.shape[0])
img2=np.repeat(img2,ratio,axis=0)
img2=np.repeat(img2,ratio,axis=1)
cv2.imshow('einstein',img2)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 人脸马赛克

In [ ]:
img=cv2.imread('./einstein.jpg')

In [9]:
ratio=10
x,y,w,h=[126,98,168,250]
face = img[y:y+h,x:x+w]
face = face[::ratio,::ratio]
face = np.repeat(face,ratio,axis=0)
face = np.repeat(face,ratio,axis=1)
img[y:y+h,x:x+w] = cv2.resize(face,(w,h))#由于face的长和宽不是10的倍数，所以上述操作之后的face不是原来的大小
# img = face_mosaic(img, x,y,w,h, ratio)
cv2.imshow('einstein',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
def face_mosaic(img, x,y,w,h, ratio=10):
    face = img[y:y+h,x:x+w]
    face = face[::ratio,::ratio]
    face = np.repeat(face,ratio,axis=0)
    face = np.repeat(face,ratio,axis=1)
    img[y:y+h,x:x+w] = cv2.resize(face,(w,h))
    return img

## 人脸检测
为使用 OpenCV 进行人脸检测,需要下载人脸级联分类器 haarcascade_frontalface_default.xml,以下是下载地址:https://github.com/opencv/opencv/tree/master/data/haarcascades

## 级联分类器CascadeClassifier
CascadeClassifier是opencv下objdetect模块中用来做目标检测的级联分类器的一个类；简而言之是滑动窗口机制+级联分类器的方式；早期opencv版本仅支持haar特征的目标检测，分别在opencv2.2和2.4之后开始支持LBP和HOG特征的目标检测。

In [18]:
import cv2
# img=cv2.imread('einstein.jpg',1)
# img=cv2.imread('cba.jpeg',1) # 多人识别
img=cv2.imread('boy1.jpg',1)
face_engine=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
faces=face_engine.detectMultiScale(img,scaleFactor=1.3,minNeighbors=5)
for (x,y,w,h) in faces:
    img = face_mosaic(img, x,y,w,h)
#     img=cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

实时捕获摄像头的数据并进行人脸检测

In [19]:
import cv2
face_cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
cap=cv2.VideoCapture(0)
while (True):
    ret,frame=cap.read()
    faces=face_cascade.detectMultiScale(frame,1.3,5)
    img=frame
    for(x,y,w,h)in faces:
#         img = face_mosaic(img, x,y,w,h)
        img=cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    cv2.imshow('FaceRecognizing',img)
    if cv2.waitKey(5)&0xFF==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()